<?php

declare(strict_types=1);

namespace Hibla\Postgres\Traits;

use Hibla\Postgres\Internals\CommandRequest;
use PgSql\Connection as PgSqlConnection;
use PgSql\Result;

/**
 * @internal
 *
 * @property-read \Hibla\Postgres\Internals\ConnectionContext $ctx
 */
trait HandlerHelperTrait
{
    /**
     * Narrows $this->ctx->connection from PgSql\Connection|resource to PgSql\Connection.
     * Safe to call whenever connection is known to be non-null.
     */
    private function getTypedConnection(): PgSqlConnection
    {
        assert($this->ctx->connection instanceof PgSqlConnection);

        return $this->ctx->connection;
    }

    /**
     * Builds an optimized casting map for the current result set based on OIDs.
     * This ensures PostgreSQL types match the MySQL Binary Protocol output.
     *
     * @return array<string, string> Map of column name to target PHP type ('int', 'float', 'bool')
     */
    protected function buildTypeCaster(Result $result): array
    {
        $cmdType = $this->ctx->currentCommand?->type;
        $isPrepared = $cmdType === CommandRequest::TYPE_EXECUTE
            || $cmdType === CommandRequest::TYPE_EXECUTE_STREAM;

        if (! $isPrepared) {
            return [];
        }

        $casters = [];
        $numFields = pg_num_fields($result);

        for ($i = 0; $i < $numFields; $i++) {
            $oid = pg_field_type_oid($result, $i);
            $name = pg_field_name($result, $i);

            if ($oid === 21 || $oid === 23 || $oid === 20) {
                $casters[$name] = 'int';
            } elseif ($oid === 700 || $oid === 701) {
                $casters[$name] = 'float';
            } elseif ($oid === 16) {
                $casters[$name] = 'bool';
            }
        }

        return $casters;
    }

    /**
     * Applies the type caster map to a raw row of strings.
     *
     * @param array<string, mixed> $row The raw associative row
     * @param array<string, string> $casters The map generated by buildTypeCaster()
     *
     * @return array<string, mixed> The typed row
     */
    protected function applyTypeCasting(array $row, array $casters): array
    {
        if (\count($casters) === 0) {
            return $row;
        }

        foreach ($casters as $col => $type) {
            if (! isset($row[$col])) {
                continue;
            }

            $value = $row[$col];

            if ($type === 'int' && \is_scalar($value)) {
                $row[$col] = (int) $value;
            } elseif ($type === 'float' && \is_scalar($value)) {
                $row[$col] = (float) $value;
            } elseif ($type === 'bool') {
                $row[$col] = ($value === 't');
            }
        }

        return $row;
    }

    /**
     * Narrows pg_fetch_assoc() keys from int|string to string.
     * PostgreSQL column names are always strings; the int possibility
     * is a PHPStan stub artifact.
     *
     * @param array<int|string, mixed> $row
     *
     * @return array<string, mixed>
     */
    private function normalizeRow(array $row): array
    {
        /** @var array<string, string|null> */
        return array_combine(
            array_map(\strval(...), array_keys($row)),
            array_values($row)
        );
    }
}
