<?php

declare(strict_types=1);

namespace Hibla\Postgres\Traits;

use Hibla\Postgres\Internals\CommandRequest;
use Hibla\Postgres\Internals\PgArrayParser;
use Hibla\Sql\Exceptions\ConstraintViolationException;
use Hibla\Sql\Exceptions\DeadlockException;
use Hibla\Sql\Exceptions\LockWaitTimeoutException;
use Hibla\Sql\Exceptions\QueryException;
use PgSql\Connection as PgSqlConnection;
use PgSql\Result;

/**
 * @internal
 *
 * @property-read \Hibla\Postgres\Internals\ConnectionContext $ctx
 */
trait HandlerHelperTrait
{
    /**
     * Narrows $this->ctx->connection from PgSql\Connection|resource to PgSql\Connection.
     * Safe to call whenever connection is known to be non-null.
     */
    private function getTypedConnection(): PgSqlConnection
    {
        assert($this->ctx->connection instanceof PgSqlConnection);

        return $this->ctx->connection;
    }

    /**
     * Builds an optimized casting map for the current result set based on OIDs.
     * This ensures PostgreSQL types match the MySQL Binary Protocol output.
     *
     * @return array<string, string> Map of column name to target PHP type ('int', 'float', 'bool')
     */
    protected function buildTypeCaster(Result $result): array
    {
        if (! $this->ctx->castPreparedTypes) {
            return []; // Skip casting if user disabled it for prepared types
        }

        $cmdType = $this->ctx->currentCommand?->type;
        $isPrepared = $cmdType === CommandRequest::TYPE_EXECUTE
            || $cmdType === CommandRequest::TYPE_EXECUTE_STREAM;

        if (! $isPrepared) {
            return [];
        }

        $casters = [];
        $numFields = pg_num_fields($result);

        for ($i = 0; $i < $numFields; $i++) {
            $oid = pg_field_type_oid($result, $i);
            $name = pg_field_name($result, $i);

            // Scalar Types
            if ($oid === 21 || $oid === 23 || $oid === 20) {
                $casters[$name] = 'int';
            } elseif ($oid === 700 || $oid === 701) {
                $casters[$name] = 'float';
            } elseif ($oid === 16) {
                $casters[$name] = 'bool';
            }
            // Array Types (Mapped to corresponding OIDs)
            elseif ($oid === 1005 || $oid === 1007 || $oid === 1016) {
                $casters[$name] = 'int_array';    // _int2, _int4, _int8
            } elseif ($oid === 1021 || $oid === 1022) {
                $casters[$name] = 'float_array';  // _float4, _float8
            } elseif ($oid === 1000) {
                $casters[$name] = 'bool_array';   // _bool
            } elseif (\in_array($oid, [
                1009, // _text
                1015, // _varchar
                1014, // _char
                2951, // _uuid
                199,  // _json
                3807, // _jsonb
                1001, // _bytea
                1231, // _numeric
            ], true)) {
                $casters[$name] = 'string_array';
            }
        }

        return $casters;
    }

    /**
     * Applies the type caster map to a raw row of strings.
     *
     * @param array<int|string, mixed> $row The raw associative row
     * @param array<string, string> $casters The map generated by buildTypeCaster()
     *
     * @return array<string, mixed> The typed row
     */
    protected function applyTypeCasting(array $row, array $casters): array
    {
        if (\count($casters) === 0) {
            /** @var array<string, mixed> */
            return $row;
        }

        foreach ($casters as $col => $type) {
            if (! \array_key_exists($col, $row) || $row[$col] === null) {
                continue;
            }

            $value = $row[$col];

            if ($type === 'int' && \is_scalar($value)) {
                $row[$col] = (int) $value;
            } elseif ($type === 'float' && \is_scalar($value)) {
                $row[$col] = (float) $value;
            } elseif ($type === 'bool') {
                $row[$col] = ($value === 't');
            } elseif (\is_string($value)) {
                $row[$col] = match ($type) {
                    'int_array' => PgArrayParser::parse($value, 'int'),
                    'float_array' => PgArrayParser::parse($value, 'float'),
                    'bool_array' => PgArrayParser::parse($value, 'bool'),
                    'string_array' => PgArrayParser::parse($value, 'string'),
                    default => $value,
                };
            }
        }

        /** @var array<string, mixed> */
        return $row;
    }

    /**
     * Extracts the error message and SQLSTATE from a failed result
     * and maps it to the specific Hibla\Sql exception class.
     */
    protected function createExceptionFromResult(Result $res): \Throwable
    {
        $rawMsg = pg_result_error($res);
        $msg = $rawMsg !== false && $rawMsg !== '' ? $rawMsg : 'Unknown query error';

        $sqlState = @pg_result_error_field($res, \PGSQL_DIAG_SQLSTATE);

        return match ($sqlState) {
            '40P01' => new DeadlockException($msg),
            '55P03' => new LockWaitTimeoutException($msg),
            default => \is_string($sqlState) && str_starts_with($sqlState, '23')
                ? new ConstraintViolationException($msg)
                : new QueryException($msg),
        };
    }
}
